name: shipyard
dependencies:
  - python>=3.9,<3.12
  - numpy
  - pip
  - pip:
    - build
    - pytest
    - pytest-cov
    - pylint
    - isort
    - black
    - flake8
    - openpulse
    - pydantic==2.5.3
    - pylint-pydantic
    - scipy
    - zhinst==25.10.3
    - matplotlib
    - pyyaml
    - deprecated
